{% set name = "pyserial" %}
{% set version = "3.5" %}
{% set sha256 = "3c77e014170dfffbd816e6ffc205e9842efb10be9f58ec16d3e8675b4925cddb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - serial
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pyserial/pyserial
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python serial port access library
  description: |
    pySerial encapsulates the access for the serial port. It provides backends
    for Python running on Windows, OSX, Linux, BSD (possibly any POSIX
    compliant system) and IronPython. The module named "serial" automatically
    selects the appropriate backend.
  doc_url: https://pyserial.readthedocs.io
  dev_url: https://github.com/pyserial/pyserial

extra:
  recipe-maintainers:
    - shaunwbell
