travis:
  secure:
    BINSTAR_TOKEN: WVO9Ci2lk9/bD3FwvrzwFBdTmIV1MyVqzYlSB0UYYckpfPza3QI5RQ6sDjl+OeO1PnKKKIG1lu+DhruvlLt5H93EesxhpujoDx2EiQi8vl1K2TeHyYzv3VUKyI7VWO+Eqj8lffOyQM6cpNT4yGuv/zJd3aBAnwZvjtt+EMyRWgZjBL6knyvUIxD2eGhr23aGuFquUTDvQ2Y5VINRR5D1aWQCsU6iJSZTOIrCSeNK/9qwDlWWYX4MVCskqY0msDBxxR5SDlqrzs2kNPdY+bP9FhYq4s4T1Q51v5mMcX0/9tUa+eVTrdwUvz3fxapzGdAxYqRGbjPGexfa2Wgy/zW1cYyLo5mESZdPdHeEjc7Xvsv/5gUofCRpJSgkhBqJTq1fONXsapmtzdUdjrw+ot52R+wp9LjWQ+CbCzoJLLPO6h5caB7uEkA6Df6CMKWuKd6f4Nn12ZVTziRUKQc+BOZLL78cLXMlkFR2zKFnXUSG+24AcWEAYGSYjNUl5v5cBsd2DOvR6dXTKLm0LwFFQkYzw62cPqEpaz8YB4Z4QtBGbtaT2ApPY3FUCHpod7SHXDY/OVqmNaIUCrMb7xnIiEH4IiEpCU1Eg+ECP2ht5NRFDMuIX4MOz+Y5GQbG0aTRegWNuS5BDuRE8OHGCattfF0kZ/6yKmqO5zgEb/Qj0IlQA5s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
