travis:
  secure:
    BINSTAR_TOKEN: k+LmaUpqfHHFBpqh8Yc83SbMVUzTnKPxIG98BfwOVdwdnqm2jfuRLAg8R7nvn9N7HuxsZq4s4iPnVJC80yMNGgjLV4H5R0amRK7Iz4ZxzHTVdLXS+E3PT1QxqLjN84uw8xfffETyA9ObRBGylUPLlRQBSI1iB5u0xzbU3LAGQ4H0PaBBluLvLoVHpVvzxZCdbJhnkz26SHvAhDT8StFRPAgdn0lnRkcrTZNNj4rooYnWkF8SYnAe1cD1OQnPXxaGWp/GjO0d59c1bRlHQz15FKtOBWswz7F+gQ5Ax2dIs7tRSaNaIBVTOn59dprWBBElLZD9Jhcdw48NxWJYQcAnGERpnBkXtIhyTrbtR4hw7jz5nRbmhxR+JjRZkkr2pzf/5vdF0XMf/SGQRDi54XkCqDL2cDJZQa7MEOBx0iVnnxA+BDMIPt9dRONCy0oFhyHtBok7hYxPuH5LWTiLKAwJsWxEDhN/CsIA4lVBcrKv4/sUmHXwfsqn8wT5q0i48noH6Vw37/DfjwGDwobZ+/Dp1XQzQ3qS5zO9syvuYD5rwLu7MtC4lNUTsMuy5UvcT6+Dw8Zo8K5QzdhKhOmq9auCqBxuuz1H9CFrFDUkribIPCfo50bqTiPnvjRUSVj29kWwiF7s2bjgWRzg9DvqBNDQzZzcUaov7X6r0sdo3LldC2I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
